site_name: "DePSI: Delft PS-InSAR processing package"
site_url: https://rogerkuou.github.io/DePSI/
repo_url: https://github.com/rogerkuou/DePSI
repo_name: DePSI

nav:
  - About DePSI: index.md
  - Install DePSI: installation.md
  - Usage:
    - DePSI Workflow: usages/depsi_workflow.md
    - Starting with a coregistered stack: usages/start_depsi.md
    - PS selection: usages/ps_selection.md
    - Network estimation: usages/network.md
    - Atmospheric phase screen estimation: usages/aps_estimation.md
    - Densification: usages/densification.md
    - Geo-coding: usages/geocoding.md
    - Post-processing: usages/postprocessing.md
    - Add Contextual information: usages/contextual_information.md
    - DS selection: usages/ds_tutorial.md
    - Designate-targets selection: usages/dtd_selection.md
  - API Reference:
    - depsi.classification: api/classification.md
    - depsi.arc_estimation: api/arc_estimation.md
    - depsi.network: api/network.md
    - depsi.atmosphere_estimation: api/atmosphere_estimation.md
    - depsi.densification: api/densification.md
    - depsi.contextual_information: api/contextual_information.md
    - depsi.transformations: api/transformations.md
    - depsi.io: api/io.md
  - Contributing: 
    - Contributing guide: CONTRIBUTING.md
    - Practical info for developers: dev_guide.md
    - Code of conduct: CODE_OF_CONDUCT.md
  - Example Notebooks:
    - DePSI example workflow: notebooks/demo_depsi_full.ipynb
    - Add Contextual Information: notebooks/demo_get_and_add_contextualinformation.ipynb
    - SARXarray and STMTools Dependencies of DePSI: notebooks/demo_sarxarray_and_stmtools.ipynb


theme:
  name: material
  custom_dir: docs/notebooks/download_button
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue
      accent: white

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
      accent: pink
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  
plugins:
- mkdocs-jupyter:
      include_source: True
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy
          docstring_options:
            ignore_init_summary: no
          merge_init_into_class: yes
          show_submodules: no

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  generator: false
  version:
    provider: mike
