[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "depsi"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "h5py",
    "matplotlib",
    "pydantic",
    "pykrige",
    "sarxarray>=1.2.3",
    "scipy",
    "stmtools>=0.1.4",
    "ruptures",
    "networkx",
    "drama",
    "asf_search",
    "sparse",
    "scikit-learn",
]
description = "Python package for interferometric synthetic aperture radar (InSAR) time series processing."
readme = "README.md"
license = {file = "LICENSE"}
authors = [
    {name = "Ou Ku", email = "o.ku@esciencecenter.nl"},
]
keywords = ["radar", "sar", "insar", "earth observation", "distributed computing"]
classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: Apache Software License',
    'Natural Language :: English',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
]

[project.optional-dependencies]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-jupyter",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mike",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pycodestyle",
    "pre-commit",
    "ruff",
    "graphviz",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocs-jupyter",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mike",
]
demo = [
    "jupyterlab",
    "contextily",
]

[tool.setuptools]
packages = ["depsi"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov --cov-report term"
testpaths = [
    "tests",
]

[tool.coverage.run]
branch = true
source = ["depsi"]

[tool.ruff]
lint.select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "B",  # flake8-bugbear
  "D",  # pydocstyle
  "I",  # isort
  "N",  # PEP8-naming
  "UP",  # pyupgrade (upgrade syntax to current syntax)
  "PLE",  # Pylint error https://github.com/charliermarsh/ruff#error-ple
]
lint.ignore = [
"D100", "D101", "D104", "D105", "D106", "D107", "D203", "D213", "D413",
"N803", "N806" # Allow capital letters in variables
] # docstring style

line-length = 120
exclude = ["docs", "build", "*.ipynb", "scripts/*", "depsi/LAMBDA.py", "experiments/*"]
# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
target-version = "py310"

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["D"]
